### ISSUE TITLE
Add DataQualityTypeCV and RelationshipTypeCV

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2ControlledVocabularies#1]
There are two additional Cvs that are ready to be added to the CV system:

DataQualityTypeCV: https://docs.google.com/spreadsheets/d/1s0RErY_87wU8_KH-KMLL5uE5XAuXyu3mNnfy7s3EVG0/edit#gid=0
RelationshipTypeCV: https://docs.google.com/spreadsheets/d/1Y-RnD4p1aGyVIZXjgJ7kE_uDjmT2Gyx8pIUCOf0hLHQ/edit#gid=0

Just load the stuff that is highlighted in green. I've got one additional CV that I'm working on (UnitsTypeCV) that I'm hoping to have done by the end of this week (if not sooner).

**Comment by denvaar** [comment]
I've added these CV's on the sandbox server and they are ready to be tested.

**Comment by horsburgh** [comment]
These look good and are ready to go to the production server.

**Comment by denvaar** [comment]
Added to the production server.

**Comment by horsburgh** [comment]
This is complete. Closing.
