### ISSUE TITLE
Add UnitsTypeCV to ODM2 CVs Website

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#11]
Need to add the terms for the UnitsTypeCV Google document to the CV website on the production server.  @denvaar should be able to create the new CV.  @jcaraballo17 - it would be great if you could deploy to the production server when he is done.  

Description of the CV:  A vocabulary for describing the type of units in which a Result is expressed.

**Comment by horsburgh** [comment]
It looks like some of the Definitions for UnitsTypes did not get uploaded into the database.  For example, see:

color
electricChargeLineDensity
electricChargePerAmountofSubstance
electricCurrentPerAngle
...

Not sure whether this is because they didn't have definitions in the source Google doc or whether this is something that happened upon import to the database.  @denvaar - need to check this.

**Comment by horsburgh** [comment]
@denvaar - when fixing this one, I don't think we can just wholesale replace with a new upload because there have been edits.

**Comment by denvaar** [comment]
The production server has been updated with this CV.

**Comment by horsburgh** [comment]
Appears to be done. Closing.
