### ISSUE TITLE
Notes carried forward into Units Type CV

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2ControlledVocabularies#14]
When the Units Type CV was marked as final an put into the web system, it still had many notes in it from my work in condensing unit types.  This means that there are a lot of notes in the system which really shouldn't be there and won't make sense to any user.  (There are references to my efforts to consolidate units systems and several frustrated comments that just shouldn't be there.)  I'm not sure if the best way to clear them out is to manually go through each term and change it in the system or to correct the google doc and upload a clean list all at once.

**Comment by horsburgh** [comment]
@SRGDamia1 - can you verify that the new UnitsTypeCV we just uploaded fixes this issue and close it if it's done?

**Comment by SRGDamia1** [comment]
This was fixed in the new upload.  Thanks!
