### ISSUE TITLE
Need to modify term view page to be a little more consistent

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#19]
On the view for an an individual term (e.g., http://vocabulary.odm2.org/actiontype/cruise/), the text that lists the term and it's definition at the top is small.  I would prefer that these just be included in the table with the other attributes as the first two rows.  This should be implemented across the views for all of the terms.

**Comment by jcaraballo17** [comment]
I removed the term from the subtitle and added it to the table. I think the definition goes well in the subtitle just below the name. You can see it both ways and tell me if you want it removed from there and put on the table.

**Comment by denvaar** [comment]
@jcaraballo17 This doesn't appear to be added to the production or sandbox project.

**Comment by aufdenkampe** [comment]
@jcaraballo17, did this fix get pushed to production? I'm just trying to figure out what issues we should close.
