### ISSUE TITLE
Navigate previous arrow buttons are not obvious

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#20]
The little up arrows that navigate to the previous page are not obvious as links to the previous page.  Could you make those into a button or do something that makes it more obvious that they are links?

**Comment by jcaraballo17** [comment]
Does this work? I'm not very fond of it and would like to change it to something else, but if it works I prefer to leave that way.

**Comment by horsburgh** [comment]
I think they are fine for now.
