### ISSUE TITLE
Modifications needed to the create new term form

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#21]
The following modifications are needed to the create new term form:
- [x] Create a separator between the information that is needed to create the term and the Submitter information.  This could be a horizontal line with the submitter information below it.
- [x] Indicate which fields are required and which are optional
- [x] Make the "Request reason" text box as large as the "Note" text box for potentially multiple line input.
- [x] Could also increase the width of the input boxes because they are very narrow compared to the container frame (unless this messes up compatibility with lots of browsers).

**Comment by aufdenkampe** [comment]
@jcaraballo17, did this fix get pushed to production? I'm just trying to figure out what issues we should close.

**Comment by jcaraballo17** [comment]
@aufdenkampe All issues from 2015 and 2016 marked as ready are deployed and can be checked at http://vocabulary.odm2.org/. I'm going to go forth and close them.
