### ISSUE TITLE
Modifications needed to the edit term form

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#22]
The following modifications are needed to the edit term form:
- [x] The text boxes on the form use inconsistently sized fonts for their contents.  See http://vocabulary.odm2.org/requests/actiontype/new/cruise/. Fix to use consistent font size
- [x] Indicate which fields are required and which are optional
- [x] Separate the submitter information from the inputs for the term. Add a horizontal line or some sort of separator to indicate what is part of the term and what is the submitter information. Group the submitter information below the inputs for the term.
- [x] Increase the size of the "Request reason" text box to be the same as the size for the "Note" text box for multi-line input.
- [x] Could also increase the width of the input boxes because they are very narrow compared to the container frame (unless this messes up compatibility with lots of browsers).

**Comment by aufdenkampe** [comment]
@jcaraballo17, did this fix get pushed to production?
