### ISSUE TITLE
Editing a term creates a new term instead of editing existing term

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#24]
Here's the process that caused this:
1.  User submitted new term
2.  Moderator accepted the new term
3.  Moderator realized that the term didn't match the name exactly
4.  Moderator submitted a change to modify the term to match the name
5.  Moderator accepted the submitted change
6.  Instead of modifying the existing term, there are now two different terms in the database.  Both have the same name (which should be impossible because names must be unique).

**Comment by aufdenkampe** [comment]
@jcaraballo17, did this fix get pushed to production?
