### ISSUE TITLE
Provenance field is getting cut off

### ISSUE THREAD

**Issue by horsburgh** [ODM2/ODM2ControlledVocabularies#25]
I just noticed that the URL in the "Provenance" field for some terms in the Relationship Type CV is getting cut off.  For example:  

http://vocabulary.odm2.org/relationshiptype/compiles/

This URL should be:

http://schema.datacite.org/meta/kernel-3/doc/DataCite-MetadataKernel_v3.1.pdf

I submitted a request to modify it, and the full URL is captured in the request, see:

http://vocabulary.odm2.org/requests/relationshiptype/fc9c98f7-f7f3-4fb1-913e-18b08f3a37be/

But when I look at the approved term after accepting the request, the field is still cut off.

Not sure if this is a front end issue, backend issue, or both?

**Comment by denvaar** [comment]
My first thought is that the field in the database is too short. I will have a look and fix it if that's the case.

**Comment by denvaar** [comment]
This was exactly the issue. I created a script to change all of the provenance and provenanceUri rows from VARCHAR(100) to VARCHAR(300). That should hopefully be enough room.

I fixed this provenance term, but if it has been chopped off anywhere else, they will need to be edited.

**Comment by denvaar** [comment]
I will leave the closing of the issue to you, Jeff.

**Comment by horsburgh** [comment]
OK - I'm happy to fix the ones that are cut off.  I'm assuming your script fixed all of the tables?

**Comment by denvaar** [comment]
Yes

**Comment by denvaar** [comment]
Both requests and normal tables for each cv.

**Comment by aufdenkampe** [comment]
Did this fix get pushed to production?
