### ISSUE TITLE
Validate Users

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2ControlledVocabularies#26]
We need to validate users so that we stop getting spammed.

**Comment by cdesyoun** [comment]
@AmberSJones I am using the url, "http://vocabulary.odm2.org/api/v1/%s/?format=skos" for validating CV in YODA file.

**Comment by horsburgh** [comment]
@cdesyoun - this issue is associated with fake vocabulary requests that we keep getting from a spam bot of some kind.  @jcaraballo17 is going to implement some sort of validation step to make sure that it is a real person making the request rather than an automated spammer.

**Comment by AmberSJones** [comment]
Sorry for the confusion!

**Comment by aufdenkampe** [comment]
@jcaraballo17, did this fix get pushed to production?
