### ISSUE TITLE
Units: Downloaded CV for units does not use the same headings as all over CV's

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2ControlledVocabularies#27]
When you download the units cv as a csv (http://vocabulary.odm2.org/api/v1/units/?format=csv), that csv doesn't have the same header as all of the other csv's.  (ie "UnitsName" instead of just "name")  This means that, among other things, the excel code in the YODA file template to pull down cv's can't pull this one down without changing the code.  I imagine the same problem would exist for any other tool trying to populate a database.

**Comment by horsburgh** [comment]
That's because its not a CV and just a list of items that can go into the ODM2 Units table. The names of the columns in the list match the names in the ODM2 Units table. One idea would be to add a separate button to the Units sheet in the template to just load the units list on that sheet.

**Comment by SRGDamia1** [comment]
Oh, right, that makes sense.

That means we definitely would need some new code to download the units into the excel YODA templates.  If the headers were the same, we could just add a units column to the CV table and the code that populates the other CV's would automatically look for it.
