### ISSUE TITLE
Reverse sorting

### ISSUE THREAD

**Issue by AmberSJones** [ODM2/ODM2ControlledVocabularies#28]
A number of the vocabularies are being sorted in reverse order, so Z --> A when they should be A --> Z.

**Comment by aufdenkampe** [comment]
@horsburgh, @sreeder, @jcaraballo17, @Maurier, any chance of addressing this bug? It would be nice to fix it before we do more demos.  Thanks!

**Comment by horsburgh** [comment]
@jcaraballo17 - Can you fix this when you have time?

**Comment by jcaraballo17** [comment]
Got it!

**Comment by aufdenkampe** [comment]
Awesome! This looks deployed to me! I'll close.
