### ISSUE TITLE
Medium Types:  Does it *have* to be "liquid aqueous"

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2ControlledVocabularies#33]
It just drives me nuts that we have simple terms like "air," "soil," and "rock" and then instead of sticking with "water" it has to be "liquid aqueous."  Can we please switch to water?  The definition already clearly states that it's a sample in water.

**Comment by horsburgh** [comment]
We adopted this term from IEDA. So, we can't get rid of the term. We could add "water" as a separate term, but then we have competing terms for what is essentially the same thing.

**Comment by SRGDamia1** [comment]
:-\  Well, I definitely don't want to add an overlapping term.  I guess I'm stuck with it then.  I just hate how it looks in a list.
