### ISSUE TITLE
Once Logged in I can't get back to the Requests page

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2ControlledVocabularies#4]
Once I am logged in, if I navigate to the main page to view any of the CVs (I navigate away from the Requests page) there is no way that I can find to get back to the requests page except to log out and then log back in. It would be nice to have a link at the top between my name and the "Logout" link that goes to the Requests page.

Jeff Horsburgh | Requests | Logout

**Comment by denvaar** [comment]
Juan says that he has added a link to the requests page.

**Comment by horsburgh** [comment]
I believe this has been implemented.  Closing.
