### ISSUE TITLE
Fix the width of the pages with tables

### ISSUE THREAD

**Issue by denvaar** [ODM2/ODM2ControlledVocabularies#5]
When I make my browser window narrow, the table on the vocabulary view page spills over the width of the page. I suggest fixing the width of the page to contain the table regardless of how narrow the browser gets. This also happens on my phone browser. Two options:

![](https://cloud.githubusercontent.com/assets/3485902/7159389/08478b44-e33f-11e4-949e-c3448e095684.png)

Fix the width of the page to contain the table
Dynamically scale the table when the page gets narrow
screenshot

**Comment by horsburgh** [comment]
@jcaraballo17 - this seems like a pretty simple styling issue that would be pretty quick to fix.

**Comment by jcaraballo17** [comment]
Done.

**Comment by horsburgh** [comment]
This still appears to be an issue on the production server.

**Comment by horsburgh** [comment]
This seemed to be a problem last night, but now it is working.  I'm going to close.
