### ISSUE TITLE
Specimen Medium vs. Sampled Medium

### ISSUE THREAD

**Issue by SRGDamia1** [ODM2/ODM2ControlledVocabularies#7]
What is the difference between these two vocabularies?  Right now they have identical terms.  Should they be combined?

**Comment by SRGDamia1** [comment]
Fixed in the specimen version, still need to do in the time series version

**Comment by SRGDamia1** [comment]
ReferenceMaterialMedium is also the same.

**Comment by horsburgh** [comment]
We had this conversation at one point.  Yes - these are initially the same.  But, I believe that we made a conscious decision to make them separate vocabularies because they have slightly different contexts.  It's likely that the terms in these will stay the same. We could consider consolidating later on if this is the case.

**Comment by SRGDamia1** [comment]
Ok.  Sorry, I didn't dig through all of the notes before posting the issue.

**Comment by aufdenkampe** [comment]
I feel that we should combine all of these into a single CV. They really should always be the same set of terms, even thought the context of their use is slightly different. If we maintain three separate lists, we will not be able to adequately manage the terms and the terms lists will differ, leading to lots of confusion.

So the question is, what do we call the new combined CV? I would argue to keep it simple, and just call it **Medium**. The definition can then be expanded to that it is a descriptor of the object that is being observed, whether in situ or ex situ.

**Comment by horsburgh** [comment]
This has been addressed.  All have been collapsed into a single CV called "Medium".  Closing.
