### ISSUE TITLE
Have page title reflect content, such as "ODM2 Sampling Feature Type CV"

### ISSUE THREAD

**Issue by aufdenkampe** [ODM2/ODM2ControlledVocabularies#9]
Right now, when I have multiple tabs open in a browser, each tab is titled "ODM2 Controlled Vocabularies". This isn't helpful if I have several term lists open at a time for reference. 

Can we change the code to make each page view have its own title? These titles should be short enough to read in a browser tab.
* Term lists, such as that at [http://vocabulary.odm2.org/samplingfeaturetype/](http://vocabulary.odm2.org/samplingfeaturetype/), should have a name similar to **ODM2 Sampling Feature Type CV** or **ODM2 CV: Sampling Feature Type**
* Term definitions, such as that at [http://vocabulary.odm2.org/samplingfeaturetype/borehole/](http://vocabulary.odm2.org/samplingfeaturetype/borehole/), should have a name similar to **ODM2 Borehole Term** or **ODM2 Term: Borehole**
I think I like the second set of syntax better.

**Comment by emiliom** [comment]
+1

**Comment by denvaar** [comment]
I will add this feature ASAP.

**Comment by denvaar** [comment]
Go ahead and see if you like what I changed it to and close the issue if it's better.

**Comment by emiliom** [comment]
Looks great.
Emilio

**Comment by horsburgh** [comment]
This appears to be done.  Closing.
